### ISSUE TITLE
Consider using l3build

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/harf#32]
Consider using l3build and having a real test suite.

**Comment by khaledhosny** [comment]
I gave it a try, but it seems to be too complex for my simple brain.

CC @u-fischer and @josephwright in case you are interested in giving a hand on this. What I need to test is basically the PDF output (including the embedded fonts) and some times I just test the output of some lua function. I currently test manually which is not very ideal.

**Comment by josephwright** [comment]
I think this should be relatively easy for @u-fischer and I to set up: I'll take a look.

**Comment by khaledhosny** [comment]
Thanks @josephwright.
