### ISSUE TITLE
harfload and tlig-ligatures

### ISSUE THREAD

**Issue by u-fischer** [khaledhosny/harf#37]
If no mode or `mode=harf` is used the tlig-ligatures don't work. Does that mean that if no mode is set, harf mode is enforced? And could harf mode support tlig?

(The current behaviour is a problem for the fonts preset by the latex format in the TU-fd-files, as they don't set a mode currently, but this can naturally be changed).

~~~
\documentclass{article}
\usepackage{harfload}
\begin{document}
{\small a--b}

\font\test={name:texgyretermes:+tlig;} 
\test
a--b

\font\test={name:texgyrebonum:mode=harf;+tlig;}
\test
a--b

\font\test={name:texgyreheros:mode=node;+tlig;}
\test
a--b

\font\test={name:texgyreheros:mode=base;+tlig;}
\test
a--b

\end{document}
~~~~

![image](https://user-images.githubusercontent.com/4047173/59837146-02c8f500-934d-11e9-8c7f-fbcdbe4690a8.png)

**Comment by khaledhosny** [comment]
> If no mode or `mode=harf` is used the tlig-ligatures don't work. Does that mean that if no mode is set, harf mode is enforced? And could harf mode support tlig?

Yes, the idea now is that if you use harfload package then all fonts go through harf mode unless another mode is explcitly set. This also fixes the fontspec issue where it would load the font with no mode set to check for its features which would route it through luaotfload and cause the font to be loaded twice.

> (The current behaviour is a problem for the fonts preset by the latex format in the TU-fd-files, as they don't set a mode currently, but this can naturally be changed).

I'd like to implement something similar to tlig feature in harf mode, but I'm not sure what is the best way to do it yet. May be I should just do the replacement while working on the node list before shaping it.
