### ISSUE TITLE
Noto Color Emoji is not copyable

### ISSUE THREAD

**Issue by emojifreak** [khaledhosny/harf#44]
```latex
\documentclass{minimal}
\usepackage{harfload}
\font\testnoto={name:Noto Color Emoji:mode=harf}
\begin{document}
\testnoto
😄👌☃⛄
\end{document}
```

The above latex file produced a correctly looking PDF, but it cannot be copy-and-pasted
and it cannot be converted to a text file by, for example, `pdftotext` program.
When I use other emoji fonts, e.g. [Symbola](http://users.teilar.gr/%7Eg1951d/) or Microsoft's Segoi UI Emoji, the resulted PDF are copy-and-pastable and can be converted to text files
by `pdftotext`.

I cannot exclude the possibility that it is a bug in Noto Color Emoji, and as harflatex is the only latex variant that can handle Noto Color Emoji, I cannot compare the above behavior with other variants of latex.

**Comment by khaledhosny** [comment]
Oh, Noto Color Emoji.

This font embedded PNGs for the color glyphs (as well as Apple Color Emoji, though in a different way).

We extract the PNGs and insert them in the PDF file, and we also try to wrap the image in `/ActualText` spans to aid with text extraction.

This however does not seem to work with images (it works with font glyphs) and I’m not sure if this is a PDF limitation or bugs in the PDF readers. I don’t know other way to embed text representation for images.

**Comment by emojifreak** [comment]
@khaledhosny thanks for your quick response. I prepared three latex files and pdfs. They have the following properties:

```latex
\pdfvariable objcompresslevel 0
\pdfvariable compresslevel 0

\documentclass{minimal}
\usepackage{harfload}
\font\testnoto={name:Noto Color Emoji:mode=harf}
\begin{document}
\testnoto
😄👌☃⛄
\end{document}
```

Its PDF file is http://www.rmatsumoto.org/testnoto.pdf
* PDF has neither `/ActualText` nor `/Font`
* It has no embedded font.
* It is not copyable by `pdftotext` in https://poppler.freedesktop.org/ or by `atril` in https://mate-desktop.org/

```latex
\pdfvariable objcompresslevel 0
\pdfvariable compresslevel 0

\documentclass{minimal}
\usepackage{harfload}
\font\test={name:Segoe UI Emoji:mode=harf}
\begin{document}
\test
😄👌☃⛄
\end{document}
```

Its PDF file is http://www.rmatsumoto.org/testsegoe.pdf
* PDF has both `/ActualText` and `/Font`
* It has `TGYTRZ+SegoeUIEmoji` embedded font
* It is copyable.

```
\pdfvariable objcompresslevel 0
\pdfvariable compresslevel 0

\documentclass{minimal}
\usepackage{harfload}
\font\test={name:Symbola:mode=harf}
\begin{document}
\test
😄👌☃⛄
\end{document}
```

Its PDF file is http://www.rmatsumoto.org/testsymbola.pdf
* PDF has `/Font` but does not have `/ActualText`
* It has `AVMWPS+Symbola` embedded font
* It is copyable.
Symbola font is available at http://users.teilar.gr/%7Eg1951d/

I will be offline for roughly 24 hours.

**Comment by khaledhosny** [comment]
That expected, except for the first PDF not having `/ActualText`. I need to check if I changed something in this area (or may be I gave up on adding actual text for PNGs when it didn’t work).

**Comment by khaledhosny** [comment]
Do you now any application/library that can produce copyable PDF using this font? I manged to use it with Pango/Cairo and the PDF contains only images and no copyable text.

**Comment by emojifreak** [comment]
> Do you now any application/library that can produce copyable PDF using this font? 

@khaledhosny Sorry for my delayed response. No, I don't. At least LibreOffice does not recognize Noto Color Emoji font while libreoffice can use Segoe UI Emoji and can produce a copyable PDF using it...

**Comment by khaledhosny** [comment]
I’m out of options how to handle this. One solution would to use a dummy outline font with a blank glyph and insert it “behind” the bitmap (bit like how Apple Color Emoji is handled, except that it has the blank glyphs itself), but that might be a bit tricky to set up.

**Comment by emojifreak** [comment]
@khaledhosny Thank you very much for your investigation. I am also fine if this is considered as a "feature" (of the font).

**Comment by khaledhosny** [comment]
Yes, as it stands now this font is pretty much uncopyable in PDF.
